Hotspot posix: build fix
battleblow/openjdk-jdk11u pull request #42
Opened 2019-06-27 16:25 UTC by devnexen

NetBSD does not define this constant, here to 16kb.

2019-06-27 16:37 UTC, bsdkurt requested changes
Hi David. Sorry I should have mentioned this in the other pull request. Could you move this up to the other compatibility defines at the top of the file like MAP_NORESERVE?

2019-06-27 16:39 UTC, devnexen commented
Sure make sense np.

2019-06-27 16:43 UTC, merged

2019-06-27 17:33 UTC, battleblow commented
FWIW, my NetBSD branch had this defined as MINSIGSTKSZ rather than putting in a hardcoded literal.  On the NetBSD 8.0/amd64 VM that ends up being 8kb rather than 16kb.

For FreeBSD, at least, this is how PTHREAD_STACK_MIN is ultimately defined as well.  I'm not sure about OpenBSD.

2019-06-27 17:35 UTC, battleblow commented
My only other NetBSD source change was to address problems with the definition of static_assert in the bundled version of harfbuzz.  The current change is just a hack to undef it on NetBSD so that the internal definition is used.  The most important make change I had was to disabled some more gcc warnings in CompileJvm.gmk

2019-06-28 22:35 UTC, krytarowski commented
The right think to do on NetBSD is to not assume any minimal size as it does not exist, it's a runtime flexible value depending on stack guard, cpu, kernel..

2019-06-28 22:36 UTC, krytarowski commented
We deliberately do not define it and portable code shall not make any assumptions that it exists, it's an optional part of POSIX.

2019-06-29 00:57 UTC, battleblow commented
Maybe so, but we have to pick **something** to use on NetBSD as the minimum stack size.  A bit of research suggests that a way to do this is to use `sysconf(_SC_THREAD_STACK_MIN)`.  I'm basing this on https://mail-index.netbsd.org/tech-userlevel/2014/08/15/msg008729.html  Unless there are objections I'd like to proceed with that.

2019-06-29 01:17 UTC, krytarowski commented
Oops, good catch. I will ask to remove this value (its return is invalid anyway).

And no, there is no need to enforce some minimal value. A portable code is supposed to not make any assumptions about this.

2019-06-29 13:32 UTC, krytarowski commented
As an example, libpthread(3) sets currently by default the stack guard to `65536` bytes.. it makes the currently hardcoded value questionable.

2019-06-29 15:43 UTC, bsdkurt commented
@battleblow Spotty internet on my trip so just a quick reply on this conversation.

I think we should leave the currently committed compatibility define at 16k (or perhaps larger) for the time being for a few reasons. @krytarowski has indicated that he intends to raise the removal of `sysconf(_SC_THREAD_STACK_MIN)` so while a good option for NetBSD I think we should wait until that coversation is had on a NetBSD mailing list and resolved. While PTHREAD_STACK_MIN is an optional value in POSIX the realiality is that either a constant or sysctl should be provided by the OS so that application developers don't have to write code that probes for the minimum value either by attempting to set via `pthread_attr_ setstacksize()` failing and increasing the value until success. The comment about stack guard size is orthogonal to the min value as POSIX defines it as additional space:

_If a thread's stack is created with guard protection, the implementation_ [allocates extra memory](http://pubs.opengroup.org/onlinepubs/7908799/xsh/pthread_attr_getguardsize.html) _at the overflow end of the stack as a buffer against stack overflow of the stack pointer._

I'm thinking we can leave it as is and when NetBSD settles on PTHREAD_STACK_MIN or `sysconf(_SC_THREAD_STACK_MIN)` it can be adjusted at that time.

@krytarowski it would be great if you could link back the conversation on `sysconf(_SC_THREAD_STACK_MIN)` so we know the direction NetBSD will be taking.

2019-06-29 16:04 UTC, krytarowski commented
I will prompt the developers, maybe there will be a change of the politics and we will define `PTHREAD_STACK_MIN` as `sysconf(_SC_THREAD_STACK_MIN)`... we will see.

2019-07-06 06:06 UTC, krytarowski commented
OK, go for `sysconf(_SC_THREAD_STACK_MIN)`. It looks like some people changed their mind. Whenever we will need to tune it, we will be able to do it inside the distribution.

2019-07-06 06:08 UTC, krytarowski commented
```
#ifndef PTHREAD_STACK_MIN
#ifdef _SC_THREAD_STACK_MIN
#define PTHREAD_STACK_MIN sysconf(_SC_THREAD_STACK_MIN)
#else
#define PTHREAD_STACK_MIN (4 * 4096)
#endif
#endif
```

or similar.

2019-07-07 00:11 UTC, battleblow commented
Thanks Kamil!  Appreciate you getting us guidance on how to do this correctly for NetBSD.  David has gone ahead and made a change to do that.