Minor cleanup, FreeBSD fixes and functionality
battleblow/openjdk-jdk11u pull request #47
Opened 2019-07-06 22:45 UTC by battleblow

2019-07-06 22:48 UTC, battleblow commented
Github seems confused about what commits are in this pull request.  I think perhaps due to the squashing of the commits going into bsd-port.

The only changes that are under review here are the commits I did today.  The earlier changes have already been merged back.  I think the right thing to do after review is for me to manually merge rather than use the UI to merge as a result.

2019-07-06 22:50 UTC, battleblow commented
@devnexen the UI isn't allowing me to add you as a reviewer for some reason, but I'd appreciate your review too.

2019-07-06 23:01 UTC, devnexen approved these changes

2019-07-06 23:01 UTC, devnexen commented on src/hotspot/os/bsd/os_perf_bsd.cpp
> +    strncpy(path, pbuf, plen);
does not have to change but since we re under BSD `strlcpy` might do ?

2019-07-07 05:56 UTC, battleblow commented
I just pushed in the NetBSD implementation for system processes too.

2019-07-08 16:05 UTC, bsdkurt requested changes
I have a minor datatype change request to the constants and noted some issues tangential to your diff regarding `now_in_nanos()` that can be addressed separately. We may also want to consider moving all uses of `malloc` to `NEW_C_HEAP_ARRAY` as we're the only os_perf_xxx.cpp implementation using malloc.

2019-07-08 16:05 UTC, bsdkurt commented on src/hotspot/os/bsd/os_perf_bsd.cpp
> +static const long NANOS_PER_MICROSEC = 1000L;
While reviewing the datatypes here I noted a few items that can be resolved in different ways. On OpenBSD/i386 long's are 4 bytes (I think also OS X/32bit). Which means `now_in_nanos()` has the 2038 problem on OpenBSD/i386. I don't think this diff needs to address that problem.

I'm not sure why the original author used a static value for NANOS_PER_SEC. I think these values would be better off as `#define` with `LL` instead of static const values. Alternatively, `static const time_t` with `LL` would also address the sizeof(long) issue here I believe.

I also noticed something else tangential to your diff, `now_in_nanos()` uses `gettimeofday(2)` which is susceptible to time moving backwards due to NTP or a sys-admin changing the time. I think we should be using `clock_gettime(CLOCK_MONOTONIC, ...)` but this can be done in a separate step if you want to get this diff in without addressing that.

2019-07-08 17:27 UTC, devnexen commented on src/hotspot/os/bsd/os_perf_bsd.cpp
> +static const long NANOS_PER_MICROSEC = 1000L;
Agreed on the last point, that is a better option.

2019-07-09 00:41 UTC, bsdkurt approved these changes
LGTM. Thanks!

2019-07-09 01:24 UTC, battleblow commented on src/hotspot/os/bsd/os_perf_bsd.cpp
> +    strncpy(path, pbuf, plen);
> does not have to change but since we re under BSD `strlcpy` might do ?

Good call.  Coming in a future pull request :)

2019-07-09 03:10 UTC, battleblow commented
I've cherry picked the relevant commits and squashed them to a single commit in bsd-port.  Merging would have brought in the ones Kurt had previously squashed as well.

What do you both think of deleting this branch and recreating it so it's cleaner wrt bsd-port?

2019-07-09 03:10 UTC, closed without merging

2019-07-09 13:54 UTC, bsdkurt commented
> What do you both think of deleting this branch and recreating it so it's cleaner wrt bsd-port?

Yes. Sounds like a good idea.